# Generated by Django 3.0.5 on 2020-05-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200504_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SCategory',
        ),
    ]
